### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by BigabilityLiu** [sshiqiao/douyin-ios-swift#4]
下载zip包后直接解压，然后打开Douyin.xcworkspace，开始编译

环境：
- macOS 10.13.6
- Xcode 10.0
<img width="325" alt="wx20180926-103145 2x" src="https://user-images.githubusercontent.com/14973015/46053940-6edc4b00-c177-11e8-80aa-35eb910c5c8f.png">

**Comment by BigabilityLiu** [comment]
主要是在Podfile中修改HandyJSON版本就可以了`pod 'HandyJSON', '~> 4.2.0'`

**Comment by sshiqiao** [comment]
666，swift版有段时间没更新了，本来想更新了再回复的，抱歉晚啦。

**Comment by BigabilityLiu** [comment]
> 666，swift版有段时间没更新了，本来想更新了再回复的，抱歉晚啦。

项目很不错，涉及到很多方面的知识值得学习，不过有一些细节可以改进。另外我更习惯用storyboard。今后如果有有趣的项目的话可以一起讨论一起做着玩

**Comment by sshiqiao** [comment]
> > 666，swift版有段时间没更新了，本来想更新了再回复的，抱歉晚啦。
> 
> 项目很不错，涉及到很多方面的知识值得学习，不过有一些细节可以改进。另外我更习惯用storyboard。今后如果有有趣的项目的话可以一起讨论一起做着玩

OK
