### ISSUE TITLE
无法在真机上运行

### ISSUE THREAD

**Issue by xiaofei730** [sshiqiao/douyin-ios-swift#5]
会报下面的编译错误
Showing All Messages
  "_swift_getFieldAt", referenced from:
      HandyJSON.Metadata.Class._propertyDescriptionsAndStartPoint() -> ([HandyJSON.Property.Description], Swift.Int32?)? in libHandyJSON.a(Metadata.o)
      HandyJSON.Metadata.Struct.propertyDescriptions() -> [HandyJSON.Property.Description]? in libHandyJSON.a(Metadata.o)
ld: symbol(s) not found for architecture arm64

**Comment by sshiqiao** [comment]
你好，我这边在真机上是可以正常运行的，上诉问题可能是cocoapods版本不一致导致的，你可以尝试删除~/Library/Developer/Xcode/DerivedData/路径下的缓存文件，再试试是否可以正常运行。
